service: aws-lambda-client
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:sa-east-1:468164258135:table/ClientTable
functions:
  addClient:
    handler: src/addClient.addClient
    events:
      - httpApi:
          path: /client
          method: post
  getClients:
    handler: src/getClients.getClients
    events:
      - httpApi:
          path: /clientes
          method: get
  deleteClient:
    handler: src/deleteClient.deleteClient
    events:
      - httpApi:
          path: /client/{id}
          method: delete

resources:
  Resources:
    ClientTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClientTable  
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH